/usr/bin/time  ./vector_add.e8 > /dev/null
/usr/bin/time  ./vector_add.e16 > /dev/null
/usr/bin/time  ./vector_add.e32  > /dev/null
/usr/bin/time  ./vector_add_ma_compiler.v8 > /dev/null
/usr/bin/time  ./vector_add_mu_compiler.v8 > /dev/null
/usr/bin/time  ./vector_add_ma_compiler.v16 > /dev/null
/usr/bin/time  ./vector_add_mu_compiler.v32 > /dev/null
/usr/bin/time  ./vector_add_ma_compiler.v32 > /dev/null
/usr/bin/time  ./vector_add_ma_iu.v32 > /dev/null
/usr/bin/time  ./vector_add_ma_ia.v32 > /dev/null
/usr/bin/time  ./vector_add_mu_iu.v32 > /dev/null
/usr/bin/time  ./vector_add_mu_ia.v32 > /dev/null
/usr/bin/time  ./vector_add.e32.3 > /dev/null
