// Generated by CoffeeScript 1.9.3
(function() {
  var args, child, decimals, e, i, nexec, nmax, nmin, nstep, prog_opt, prog_orig, ref, ref1, ref2, usage;

  child = require('child_process');

  e = child.execSync;

  usage = function() {
    return console.error("Usage: script prog_orig prog_opt nmin nmax nstep nexec\n\nprog_orig  - Executable of the original program\nprog_opt   - Executable of the optimized program\nnmin, nmax - Minimum and maximum number of decimals\nnstep      - Step for the nmin to nmax decimal loop\nnexec      - Number of executions to do average of execution time");
  };

  args = process.argv.slice(2);

  if (args.length !== 6) {
    usage();
  }

  prog_orig = args[0], prog_opt = args[1], nmin = args[2], nmax = args[3], nstep = args[4], nexec = args[5];

  for (decimals = i = ref = nmin, ref1 = nmax, ref2 = nstep; ref2 > 0 ? i <= ref1 : i >= ref1; decimals = i += ref2) {
    console.log(decimals);
  }

}).call(this);
